### ISSUE TITLE
ICA not configured correctly - missing ics4wrapper parameter

### ISSUE THREAD

**Issue by joe-bowman** [OmniFlix/omniflixhub#199]
On attempting to send an ICA packet, the transaction causes a panic (which is caught and reverted), due to a nil reference. The reference in question is the value of ics4wrapper in the ICA Host Keeper.

This should be passed in at construction, and should take the value of the IBC Channel Keeper (or ics4 stack in the case of middlewares).

ICA Keeper constructor definition can be found here: 
https://github.com/cosmos/ibc-go/blob/af8b6afc4ed8145fa25e93fbdc5d779e14e1960d/modules/apps/27-interchain-accounts/host/keeper/keeper.go#L69

Omniflix's instantiation as follows:
https://github.com/OmniFlix/omniflixhub/blob/1bc33eba9da10d94a1e5398c55a34cec0f1eb47b/app/keepers/keepers.go#L450

The line that panics as a result:
https://github.com/cosmos/ibc-go/blob/af8b6afc4ed8145fa25e93fbdc5d779e14e1960d/modules/apps/27-interchain-accounts/host/keeper/keeper.go#L108

**Comment by joe-bowman** [comment]
For reference, the entire panic:
```
2024-12-30T19:26:46.426042Z ERROR ThreadId(69) relay_recv_packet_and_timeout_messages{src_chain=quicksilver-2 src_port=icacontroller-omniflixhub-1.delegate src_channel=channel-233 dst_chain=omniflixhub-1}:send_messages_and_wait_commit{chain=omniflixhub-1 tracking_id=packet-recv}:send_tx_with_account_sequence_retry{chain=omniflixhub-1 account.sequence=16}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "recovered: runtime error: invalid memory address or nil pointer dereference\nstack:\ngoroutine 359263011 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func5({0x468cb20, 0x78a44e0})\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:74 +0x25\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func7({0x468cb20?, 0x78a44e0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:42 +0x2d\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x468cb20, 0x78a44e0}, 0xc075553f80?)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:31 +0x2f\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x468cb20, 0x78a44e0}, 0xc1055ac1e8?)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:36 +0x53\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/baseapp.go:842 +0x156\npanic({0x468cb20?, 0x78a44e0?})\n\truntime/panic.go:770 +0x132\ngithub.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.Keeper.GetAppVersion(...)\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/apps/27-interchain-accounts/host/keeper/keeper.go:145\ngithub.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.Keeper.getAppMetadata({{0x597d228, 0xc002227970}, {0x59f2b10, 0xc00128f610}, {0x597e478, 0xc001645800}, {0x0, 0x0}, {0x59ac190, 0xc001a68850}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/apps/27-interchain-accounts/host/keeper/keeper.go:150 +0xab\ngithub.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.Keeper.OnRecvPacket({{0x597d228, 0xc002227970}, {0x59f2b10, 0xc00128f610}, {0x597e478, 0xc001645800}, {0x0, 0x0}, {0x59ac190, 0xc001a68850}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/apps/27-interchain-accounts/host/keeper/relay.go:27 +0x15b\ngithub.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host.IBCModule.OnRecvPacket({{{0x597d228, 0xc002227970}, {0x59f2b10, 0xc00128f610}, {0x597e478, 0xc001645800}, {0x0, 0x0}, {0x59ac190, 0xc001a68850}, ...}}, ...)\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/apps/27-interchain-accounts/host/ibc_module.go:126 +0x1d8\ngithub.com/cosmos/ibc-go/v8/modules/core/keeper.Keeper.RecvPacket({{0x0, 0x0}, {0x59c9180, 0xc00128f610}, {{0x597d228, 0xc002227930}, {0x59c9180, 0xc00128f610}, {0x597d888, 0xc002227ba0}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/core/keeper/msg_server.go:493 +0xd95\ngithub.com/cosmos/ibc-go/v8/modules/core/04-channel/types._Msg_RecvPacket_Handler.func1({0x59ac5f0?, 0xc081efd2f0?}, {0x4af9c20?, 0xc10757d1e0?})\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/core/04-channel/types/tx.pb.go:2267 +0xce\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2.1({0x59abd30, 0xc075408e08}, {0xc1055b1520?, 0x18fc8e5?}, 0x358?, 0xc0bfeec150)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/msg_service_router.go:175 +0x8a\ngithub.com/cosmos/ibc-go/v8/modules/core/04-channel/types._Msg_RecvPacket_Handler({0x4bd7900, 0xc0019cc180}, {0x59abd30, 0xc075408e08}, 0x525ae68, 0xc0b43af900)\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/core/04-channel/types/tx.pb.go:2269 +0x143\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2({{0x59abd68, 0x7abaca0}, {0x59c9ab0, 0xc075348800}, {{0x0, 0x0}, {0xc0015e1640, 0xd}, 0xecb00e, {0x1b8c5308, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/msg_service_router.go:198 +0x37f\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x59abd68, 0x7abaca0}, {0x59c9ab0, 0xc075348800}, {{0x0, 0x0}, {0xc0015e1640, 0xd}, 0xecb00e, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/baseapp.go:1021 +0x1e6\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc00190afc8, 0x2, {0xc04ccf1500, 0x64ff, 0x6a80})\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/baseapp.go:959 +0x126c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/test_helpers.go:28\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x59d2f38, 0xc0019e1410}, 0x0, {0x0, 0x0}, {0x59f2b10, 0xc00128f610}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/x/auth/tx/service.go:98 +0x12c\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler.func1({0x59ac5f0?, 0xc00b71f380?}, {0x4aa7b40?, 0xc033739ce0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/types/tx/service.pb.go:1443 +0xcb\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1({0x59ac5f0, 0xc0decc7aa0}, {0x4aa7b40, 0xc033739ce0}, 0xc033739d00?, 0xc0af55ae88)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/grpcserver.go:67 +0x458\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.2.1({0x59ac5f0?, 0xc0decc7aa0?}, {0x4aa7b40?, 0xc033739ce0?})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x59ac5f0?, 0xc0decc7aa0?}, {0x4aa7b40?, 0xc033739ce0?}, 0x0?, 0xc0af55ae88?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33 +0xb0\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.2({0x59ac5f0, 0xc0decc7aa0}, {0x4aa7b40, 0xc033739ce0}, 0xc033739d00, 0x28?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x123\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x4a68ce0, 0xc0007a8f00}, {0x59ac5f0, 0xc0decc7aa0}, 0xc074665c80, 0xc0decc7ad0)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/types/tx/service.pb.go:1445 +0x143\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2({0x4a68ce0, 0xc0007a8f00}, {0x59ac5f0, 0xc0decc7aa0}, 0xc074665c80, 0xc074de8d80?)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.9/baseapp/grpcserver.go:81 +0x112\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc001aff800, {0x59ac5f0, 0xc0a550ea80}, {0x59c60c0, 0xc00facbb00}, 0xc074de8d80, 0xc002317680, 0xc001239340, 0x0)\n\tgoogle.golang.org/grpc@v1.64.1/server.go:1379 +0xdf8\ngoogle.golang.org/grpc.(*Server).handleStream(0xc001aff800, {0x59c60c0, 0xc00facbb00}, 0xc074de8d80)\n\tgoogle.golang.org/grpc@v1.64.1/server.go:1790 +0xe8b\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1()\n\tgoogle.golang.org/grpc@v1.64.1/server.go:1029 +0x8b\ncreated by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 359263010\n\tgoogle.golang.org/grpc@v1.64.1/server.go:1040 +0x125\n: panic [cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:72] with gas used: '373236'", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "15511566"} }
```

where the relevant bit is:
```
github.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.Keeper.GetAppVersion(...)\n\tgithub.com/cosmos/ibc-go/v8@v8.4.0/modules/apps/27-interchain-accounts/host/keeper/keeper.go:145
```
